name: Spring Cars

on:
  pull_request:
    branches:
      - devops
  push:
    branches:
      - devops
  workflow_dispatch:
#on:
#  workflow_dispatch: 
# We can use for manual trigger this feature


jobs:
  say-my-name:
    runs-on: syr-org-v1
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Write my console
      run: echo "Hi from spring-cars named app"
    - name: "Delete unused docker objects"
      shell: pwsh
      run: |
        docker images
        Start-Sleep 5
        $images=docker images | grep signum | awk '{print $3}'
        Write-Host $images
        Foreach($imageDigest in $images){ docker image rmi -f $imageDigest}
        docker images | Out-File -FilePath registeredImages.txt
        Get-ChildItem
        Get-Content registeredImages.txt
    - name: "Delete registered named file"
      shell: bash
      run: |
        rm -rf registeredImages.txt
    - name: Run tests
      run: |
          # Run tests here
          if [ $? -ne 0 ]; then
            if [ ${{ steps.<step_name>.outcome }} == 'failure' ]; then
              failure("Tests failed with an error")
            else
              failure("Tests failed with a warning")
            fi
          fi
     
        
